"""
Example failing tests authored by @pries-test for STA-001 Task 1.

File: tests/services/test_broadcast.py
Generated by stdd-test-author-constrained skill.

Failure classification (initial run, before @pries-make implementation):
- test_subscriber_added_on_connect: MISSING_BEHAVIOR (Broadcaster class doesn't exist)
- test_subscriber_removed_on_disconnect: MISSING_BEHAVIOR
- test_broadcast_reaches_all_subscribers: MISSING_BEHAVIOR
- test_broadcast_latency_under_200ms: MISSING_BEHAVIOR
- test_slow_consumer_does_not_block_fanout: MISSING_BEHAVIOR

All five qualify as RED. Hand off to @pries-make in tdd mode.
"""
import asyncio
import time

import pytest


@pytest.mark.asyncio
async def test_subscriber_added_on_connect():
    """AC-1: connect() registers a subscriber for a scene."""
    from app.services.broadcast import Broadcaster  # noqa: WPS433

    bc = Broadcaster()
    queue: asyncio.Queue = asyncio.Queue()
    await bc.connect(scene_id="scene-1", subscriber=queue)
    assert bc.subscriber_count("scene-1") == 1


@pytest.mark.asyncio
async def test_subscriber_removed_on_disconnect():
    """AC-5: disconnect() removes the subscription."""
    from app.services.broadcast import Broadcaster  # noqa: WPS433

    bc = Broadcaster()
    queue: asyncio.Queue = asyncio.Queue()
    await bc.connect(scene_id="scene-1", subscriber=queue)
    await bc.disconnect(scene_id="scene-1", subscriber=queue)
    assert bc.subscriber_count("scene-1") == 0


@pytest.mark.asyncio
async def test_broadcast_reaches_all_subscribers():
    """AC-2: broadcast() delivers to every connected subscriber."""
    from app.services.broadcast import Broadcaster  # noqa: WPS433

    bc = Broadcaster()
    queues = [asyncio.Queue() for _ in range(5)]
    for q in queues:
        await bc.connect(scene_id="scene-1", subscriber=q)

    payload = {"pool": 7, "version": 42}
    await bc.broadcast(scene_id="scene-1", payload=payload)

    for q in queues:
        msg = await asyncio.wait_for(q.get(), timeout=1.0)
        assert msg == payload


@pytest.mark.asyncio
async def test_broadcast_latency_under_200ms():
    """AC-2 / NFR-PERF-002: sync latency under 200 ms with 50 subscribers."""
    from app.services.broadcast import Broadcaster  # noqa: WPS433

    bc = Broadcaster()
    queues = [asyncio.Queue() for _ in range(50)]
    for q in queues:
        await bc.connect(scene_id="scene-1", subscriber=q)

    start = time.perf_counter()
    await bc.broadcast(scene_id="scene-1", payload={"pool": 1})
    # Drain
    for q in queues:
        await asyncio.wait_for(q.get(), timeout=0.5)
    elapsed_ms = (time.perf_counter() - start) * 1000

    assert elapsed_ms < 200, f"fanout took {elapsed_ms:.1f} ms (NFR-PERF-002 budget 200 ms)"


@pytest.mark.asyncio
async def test_slow_consumer_does_not_block_fanout():
    """Resilience: a queue that is not drained must not block other subscribers."""
    from app.services.broadcast import Broadcaster  # noqa: WPS433

    bc = Broadcaster(send_timeout_ms=250)
    fast_q: asyncio.Queue = asyncio.Queue()
    slow_q: asyncio.Queue = asyncio.Queue(maxsize=1)
    await slow_q.put({"old": "msg"})  # already full, will block on put

    await bc.connect(scene_id="scene-1", subscriber=fast_q)
    await bc.connect(scene_id="scene-1", subscriber=slow_q)

    start = time.perf_counter()
    await bc.broadcast(scene_id="scene-1", payload={"pool": 9})
    elapsed_ms = (time.perf_counter() - start) * 1000

    # Fast subscriber received the message; slow one was dropped after timeout.
    assert (await asyncio.wait_for(fast_q.get(), timeout=0.5)) == {"pool": 9}
    assert elapsed_ms < 400, f"slow consumer blocked fanout for {elapsed_ms:.1f} ms"
    assert bc.subscriber_count("scene-1") == 1, "slow consumer should be evicted"
